name: CI

on: [ "push", "pull_request" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.nuget/packages
            ~/.cache/bepinex
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - uses: actions/checkout@v2

        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      - name: Run the Cake script
        uses: cake-build/cake-action@v1
        with:
          verbosity: Diagnostic

      - uses: actions/upload-artifact@v2
        with:
          name: Laboratory.dll
          path: Laboratory/bin/Release/net6.0/Laboratory.dll

      - uses: actions/upload-artifact@v2
        with:
          name: Laboratory.nupkg
          path: Laboratory/bin/Release/Laboratory.*.nupkg

      - uses: actions/upload-artifact@v2
        with:
          name: Jungle.dll
          path: Jungle/bin/Release/net6.0/Jungle.dll

      - uses: actions/upload-artifact@v2
        with:
          name: Jungle.nupkg
          path: Jungle/bin/Release/Jungle.*.nupkg

      - name: Push
        run: dotnet nuget push **/bin/Release/*.nupkg --source https://nuget.pkg.github.com/Among-Us-Modding/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
